import '../styles/globals.css';
import type { AppProps } from 'next/app';
import { SessionProvider } from 'next-auth/react';
import { LoginRequired } from '../src/components/LoginRequired';
import Head from 'next/head';

function MyApp({ Component, pageProps: { session, ...pageProps } }: AppProps) {
  return (
    <SessionProvider session={session}>
      <Head>
        <title> White-Lucida </title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.png' />
      </Head>
      <LoginRequired>
        <Component {...pageProps} />
      </LoginRequired>
    </SessionProvider>
  );
}

export default MyApp;
