import Head from 'next/head';
import Link from 'next/link';
import { NextPage } from 'next';
import { useState } from 'react';
import {
  APIActionRowComponent,
  APIEmbed,
  APIMessageComponent,
  RESTPostAPIWebhookWithTokenJSONBody,
} from 'discord-api-types';

import styles from '../styles/New.module.css';

import { Form } from '../src/components/Form';
import axios from 'axios';

const New: NextPage = () => {
  const [channelUrl, setChannelUrl] = useState('');
  const save = (address: string, body: RESTPostAPIWebhookWithTokenJSONBody) => {};

  const onSubmit = (embeds: APIEmbed[], actionRows: APIActionRowComponent[]) => {
    const data = {
      url: channelUrl,
      embeds,
      actionRows,
    };
    axios.post('/api/send', data);
  };

  return (
    <section>
      <Head>
        <title> 新規メッセージ </title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <header className={styles.header}>
        <Link href='/'>← 戻る</Link>
      </header>

      <main className={styles.main}>
        <h1> 新規メッセージ </h1>
        <p> 新しいメッセージを作成します。 </p>

        <h1> チャンネルのURL </h1>
        <p> メッセージを投稿するDiscordチャンネルのURLを入力してください。</p>
        <p>
          <input
            className={styles.channelURL}
            onChange={(e) => setChannelUrl(e.target.value)}
            value={channelUrl ?? ''}
          />
        </p>

        <h1> 入力フォーム </h1>
        <p> 内容を入力してください。 </p>
      </main>
      <Form onSubmit={onSubmit}></Form>
    </section>
  );
};

export default New;
